export const DEFAULT_TIMEOUT_MS = 10000;
export const RETRY_BASE_DELAY_MS = 1000;
export const MAX_RETRY_COUNT = 3;

export const STATUS_CODE = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  CLIENT_CLOSED_REQUEST: 499,
} as const;

export type StatusCode = (typeof STATUS_CODE)[keyof typeof STATUS_CODE];

export const DEFAULT_RETRY_ON: StatusCode[] = [
  STATUS_CODE.REQUEST_TIMEOUT,
  STATUS_CODE.TOO_MANY_REQUESTS,
  STATUS_CODE.INTERNAL_SERVER_ERROR,
  STATUS_CODE.BAD_GATEWAY,
  STATUS_CODE.SERVICE_UNAVAILABLE,
  STATUS_CODE.GATEWAY_TIMEOUT,
];
